### YamlMime:UniversalReference
items:
  - uid: azure-servicefabric.ValidationFailedChaosEvent
    name: ValidationFailedChaosEvent
    fullName: ValidationFailedChaosEvent
    children:
      - azure-servicefabric.ValidationFailedChaosEvent.kind
      - azure-servicefabric.ValidationFailedChaosEvent.reason
      - azure-servicefabric.ValidationFailedChaosEvent.timeStampUtc
    langs:
      - typeScript
    type: interface
    summary: 在驗證期間的失敗對應的混亂事件。
    extends:
      name: azure-servicefabric.ChaosEvent
    package: azure-servicefabric
  - uid: azure-servicefabric.ValidationFailedChaosEvent.kind
    name: kind
    fullName: kind
    children: []
    langs:
      - typeScript
    type: property
    summary: 多型的鑑別子
    syntax:
      content: 'kind: string'
      return:
        type:
          - string
    package: azure-servicefabric
  - uid: azure-servicefabric.ValidationFailedChaosEvent.reason
    name: reason
    fullName: reason
    children: []
    langs:
      - typeScript
    type: property
    summary: 描述為何產生 ValidationFailedChaosEvent。 這可能是因為多個 MaxPercentUnhealthyNodes MaxClusterStabilizationTimeout 超過狀況不良。 做為字串，因此將處於 ValidationFailedChaosEvent 的原因與 Reason 屬性。
    optional: true
    syntax:
      content: 'reason?: string'
      return:
        type:
          - string
    package: azure-servicefabric
  - uid: azure-servicefabric.ValidationFailedChaosEvent.timeStampUtc
    name: timeStampUtc
    fullName: timeStampUtc
    children: []
    langs:
      - typeScript
    type: property
    summary: UTC 時間戳記時產生這個混亂事件。
    syntax:
      content: 'timeStampUtc: Date'
      return:
        type:
          - Date
    package: azure-servicefabric
references:
  - uid: azure-servicefabric.ChaosEvent
    name: ChaosEvent
    spec.typeScript:
      - name: ChaosEvent
        fullName: ChaosEvent
        uid: azure-servicefabric.ChaosEvent